### ISSUE TITLE
Display image in GUI

### ISSUE THREAD

**Issue by jacobbieker** [tjlagrow/Meme-Machine#1]
Probably have to download the image to the client computer, then load it from disk. Current idea would be that the QGraphicsView overwrites whatever image was downloaded before with the new one, just to simplify loading it. Displaying an image to edit means the GUI will now have two GraphicsViews, one for displaying the image from the chat, and one to display and edit before sending it to the chat.

**Comment by tjlagrow** [comment]
We got an image to download!

**Comment by jacobbieker** [comment]
Then it seems that the issue is solved!
